[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/serveUpload"
  status = 200